name: Clean wokflows
on:
    workflow_dispatch:
    schedule:
      - cron: "0 0 * * *"
jobs:
    delete_runs:
        runs-on: ubuntu-latest
        if: ${{ always() }}
        steps:
          - name: Delete workflow runs
            uses: dmvict/clean-workflow-runs@v1.2.1
            with:
              token: ${{ secrets.DELETE_WORKFLOW }}
              save_period: 30